"""Add DropdownOption table

Revision ID: 2f68fd399e07
Revises: 
Create Date: 2026-03-07 20:10:10.724724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f68fd399e07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dropdown_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'value', name='uq_dropdown_category_value')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_audit_logs_table_record'))
        batch_op.drop_constraint(batch_op.f('audit_logs_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_customers_name'))
        batch_op.drop_index(batch_op.f('idx_customers_phone'))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_items_order_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('order_items_inventory_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventory', ['inventory_id'], ['id'])
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])
        batch_op.drop_column('total_price')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_orders_order_no'))
        batch_op.drop_constraint(batch_op.f('orders_customer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])
        batch_op.drop_column('balance_amount')

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.alter_column('addition',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('prescriptions_customer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('prescriptions_customer_id_fkey'), 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('addition',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_amount', sa.NUMERIC(precision=10, scale=2), sa.Computed('(total_amount - advance_amount)', persisted=True), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('orders_customer_id_fkey'), 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_orders_order_no'), ['order_no'], unique=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), sa.Computed('((quantity)::numeric * unit_price)', persisted=True), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_items_inventory_id_fkey'), 'inventory', ['inventory_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('order_items_order_id_fkey'), 'orders', ['order_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_customers_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('idx_customers_name'), ['name'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audit_logs_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_audit_logs_table_record'), ['table_name', 'record_id'], unique=False)

    op.drop_table('dropdown_options')
    # ### end Alembic commands ###
